### ISSUE TITLE
Implement GitHub features

### ISSUE THREAD

**Issue by FelipeRamos1202** [FelipeRamosPersonalProjects/dev-task-manager-BE#105]
## Description
For a better view of this implementation planning, I will create a fluxogram of all developer procedures, so I can track which features have more impact on my day-by-day.

## Tasks
- [x] #107
- [x] #125
- [x] #219
- [ ] Implement fetch methods
- [ ] Improve branch transitions
- [ ] Documentation

## Procedures related to GitHub
- [ ] PM **assigns the ticket to a developer**.
- [ ] The developer starts the **investigation** and receives a **discovery task**.
- [ ] When the **estimation is approved**, the **QA team creates a new dev task to track the time** during the development of the ticket.
- [ ] During the development the developer usually **creates a draft branch** to implement the ticket, before creating the definitive one.
- [ ] After it's all finished, he is ready to **create the definitive branch** to create the PR.
- [ ] With the branch created, the developer starts to **create the PR.**
- [ ] To the PR, it's required to add a **specific format of PR description according to the related project**. But one thing that all projects required are to add the **file changes description**. So the developer needs to **document it and describe** the changes done.
- [ ] The **reviewers can make some comments** to the developer and he needs to fix them.
- [ ] Sometimes some mistakes can happen, such as creating a **PR with the name out of the company standard**.
- [ ] Since the PR was already merged at this stage, it will need a **v2 PR**
