### ISSUE TITLE
Minimum required to start GibHub side

### ISSUE THREAD

**Issue by FelipeRamos1202** [FelipeRamosPersonalProjects/dev-task-manager-BE#107]
## Description
Check below the targets of dev daily problems to solve on this issue.
- [x] PM **assigns the ticket to a developer**.
- [x] The developer starts the **investigation** and receives a **discovery task**.
- [x] When the **estimation is approved**, the **QA team creates a new dev task to track the time** during the development of the ticket.
- [x] To the PR, it's required to add a **specific format of PR description according to the related project**. But one thing that all projects required are to add the **file changes description**. So the developer needs to **document it and describe** the changes done.
- [x] Sometimes some mistakes can happen, such as creating a **PR with the name out of the company standard**.

## Tasks
- [x] #108
- [x] #109
