### ISSUE TITLE
Ticket and Tasks

### ISSUE THREAD

**Issue by FelipeRamos1202** [FelipeRamosPersonalProjects/dev-task-manager-BE#108]
## Description
This is a piece of the target breakdown for the GitHub functionalities:
- [x] PM **assigns the ticket to a developer**.
- [x] The developer starts the **investigation** and receives a **discovery task**.
- [x] When the **estimation is approved**, the **QA team creates a new dev task to track the time** during the development of the ticket.

## Keywords
- Assigns the ticket to a developer
- Investigation
- Discovery task
- Estimation is approved
- QA team creates a new dev task to track the time

## Tasks
- [x] #110
- [x] #111
