### ISSUE TITLE
 Create method to create a new branch

### ISSUE THREAD

**Issue by FelipeRamos1202** [FelipeRamosPersonalProjects/dev-task-manager-BE#135]
## Tasks
- [x] Create the method createBranch on RepoManager
- [x] Improve the method checkout of RepoManager
- [x] Create the stash method
