### ISSUE TITLE
Create an PR stage and resume approach

### ISSUE THREAD

**Issue by FelipeRamosDev** [FelipeRamosPersonalProjects/dev-task-manager-BE#197]
## Solution
- [x] Create new fields under tasks called **subTasks ([ ObjectId ])** and **parentTask ( ObjectId )**
- [x] Create a new field under tasks called **prStage**
- [x] Create a new field under tasks called **type**
- [x] Create a new field under tasks called **isCurrentVersion** indicating that the task is current one
- [x] The tasks should have two type, **"master-task"** and **"sub-task"**. Master tasks doesn't have parent task, but sub tasks have
- [x] Every time before start a new process, check if the current branch name is available, if don't increase the task version and try again
- [x] Every time a user start a new PR process, it should be displayed a question if he wants to continue the current PR process, or if he wants to create a new one. If choose to create a new one, another question should be presented asking if he wants to delete de incomplete PR, or leave as it is.

## Tasks
- [x] #200
- [x] #202
- [x] #204
