### ISSUE TITLE
Create the basics methods

### ISSUE THREAD

**Issue by FelipeRamos1202** [FelipeRamosPersonalProjects/dev-task-manager-BE#52]
## Tasks
- [x] Pre-create a checkout method
- [x] Pre-create a addChanges method
- [x] Pre-create a commit method
- [x] Pre-create a push method
